

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: 12341234
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 1
  jpa:
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    # spring boot 2 점대에서
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: none


